config/routes.rb
Catfood::Application.routes.draw do
  devise_for :users
  resources :price_logs
  resources :categories
  resources :product_infos

  namespace :admin do
    resources :product_infos
  end

  namespace :users do
    resources :price_logs 
  end

  namespace :users do
    resources :price_logs do
      member do
        get :product_info_logs
      end
    end
  end

  root 'price_logs#index'

  

end

app/models/capacity.rb
class Capacity < ActiveRecord::Base
  belongs_to :sub_capacity, :class_name => "Capacity", :foreign_key => "sub_capacity_id"
  has_many :main_capacity, :class_name => "Capacity"

  has_many :price_logs

  has_many :product_info_capacityships
  has_many :product_infos, :through => :product_info_capacityships
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_infos
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :product_info_locationships
  has_many :product_infos, :through => :product_info_locationships

  has_many :price_logs
end

app/models/price_log.rb
class PriceLog < ActiveRecord::Base
  belongs_to :user
  belongs_to :product_info
  belongs_to :location
  belongs_to :capacity

  validates_presence_of :price, :log_date, :product_info_id, :location_id, :capacity_id, :amount

  before_save :calculate_total
  protected
  def calculate_total
    self.total = self.amount * self.price
  end
end

app/models/product_info.rb
class ProductInfo < ActiveRecord::Base
  belongs_to :category # 單數
  has_many :price_logs
  has_many :product_info_locationships
  has_many :locations, :through => :product_info_locationships
  has_many :product_info_capacityships
  has_many :capacities, :through => :product_info_capacityships
end

app/models/product_info_capacityship.rb
class ProductInfoCapacityship < ActiveRecord::Base
  belongs_to :product_info
  belongs_to :capacity
end

app/models/product_info_locationship.rb
class ProductInfoLocationship < ActiveRecord::Base
  belongs_to :product_info
  belongs_to :location
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :price_logs
end

app/controllers/admin/product_infos_controller.rb
class Admin::ProductInfosController < ApplicationController
  before_filter :authenticate

  def index
    @product_infos = ProductInfo.all
  end

  protected
    def authenticate
       authenticate_or_request_with_http_basic do |user_name, password|
           user_name == "username" && password == "password"
       end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    render text: "Hello World"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/price_logs_controller.rb
class PriceLogsController < ApplicationController

  def index
    @price_logs = PriceLog.page(params[:page]).per(5)
  end

  def show
    @price_log = PriceLog.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/controllers/product_infos_controller.rb
class ProductInfosController < ApplicationController
  before_filter :find_product_info, :only => [:destroy]

  def index
    @product_infos = ProductInfo.all
  end

  def new
    @product_info = ProductInfo.new
  end

  def create
    @product_info = ProductInfo.new(product_info_params)
    if @product_info.save
      flash[:notice] = "Successfully created..."
      redirect_to product_infos_path
    else
      render :action => :new
    end
  end

  def destroy
    @product_info.destroy

    flash[:alert] = "event was successfully deleted"
    redirect_to product_infos_path
  end

protected

  def find_product_info
    @product_info = ProductInfo.find(params[:id])
  end

  def product_info_params
    params.require(:product_info).permit(:vendor, :name, :category_id)
  end
end

app/controllers/users/price_logs_controller.rb
class Users::PriceLogsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @price_logs = current_user.price_logs.page(params[:page]).per(5)
  end

  def product_info_logs
    @price_logs_for_product_info = PriceLog.joins(:product_info).where(:user_id => current_user.id, :product_info_id => params[:id])
    product_info = ProductInfo.find(params[:id])
    @locations_for_product_info = product_info.locations
    @capacities_for_product_info = product_info.capacities
    respond_to do |format|
      format.js
    end
  end

  def new
    @page_title = "新的產品購買記錄"
    @price_log = PriceLog.new
  end

  def create
    #@product_info = ProductInfo.find( params[:format] )
    #@location = Location.find(params[:location])
    @price_log = PriceLog.new(price_logs_params)
    if @price_log.save
      flash[:notice] = "Successfully created..."

      current_user.price_logs << @price_log
      redirect_to users_price_logs_path
    else
      render :action => :new
    end
  end

protected
  def price_logs_params
    params.require(:price_log).permit(:price, :log_date, :capacity_id, :product_info_id, :location_id)
  end
end

app/helpers/admin/product_infos_helper.rb
module Admin::ProductInfosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/price_logs_helper.rb
module PriceLogsHelper
end

app/helpers/product_infos_helper.rb
module ProductInfosHelper
  def category_options
        Category.all.map{ |c| [c.name, c.id] }
  end
end

app/helpers/users/price_logs_helper.rb
module Users::PriceLogsHelper
  def product_info_options
    ProductInfo.all.map{ |c| [c.vendor + ' ' + c.name + '(' + c.category.try(:name) + ')', c.id] }
  end
end

app/views/admin/product_infos/index.html.erb
<ul>
<% @product_infos.each do |info| %>
  <li>
    <%= info.id %>
    <%= info.vendor %>
    <%= info.name %>
    <br>
    類別:<%= info.category.try(:name) %>
    <br>
    <%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    價格記錄: <%= link_to 'add log', new_price_log_path(info) %> <br>
    <% info.price_logs.each do |log| %>
      <%= log.price %>
      <%= log.location %>
      <%= log.capacity %>
      <%= log.cap_unit %>
      <%= log.log_date %>
      <br>
    <% end %>
  </li>
<% end %>
</ul>

<%= link_to 'new product info', new_product_info_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "App_Name" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/price_logs/_price_log.html.erb
<%= @price_log.price %><br>
ajax<br>
<p><%= link_to 'Back to index', price_logs_path %> </p>

app/views/price_logs/index.html.erb
<ul>
<% @price_logs.each do |log| %>
  <li>
    <%= log.price %>
    <%#= log.location %>
    <%#= log.capacity %>
    <%#= log.cap_unit %>
    <%= log.log_date %>
    <br>

    <%= log.product_info.vendor %>
    <%= log.product_info.name %>
    <br>
    類別:<%= log.product_info.category.try(:name) %>
    <br>
    <%= link_to '詳細', price_log_path(log), :remote => true, "data-type" => "script" %><br> 

  </li>
<% end %>
</ul>

<%= paginate @price_logs %><br> 

<%= link_to '登入個人購買記錄頁面', users_price_logs_path %><br> 

<div id="content">
</div>

app/views/price_logs/new.html.erb
<h1><%= @product_info.vendor %></h1>
<h2><%= @product_info.name %></h2>
<%= form_for @price_log, :url => price_logs_path(@product_info) do |f| %>
    <%= f.label :price, "Price" %>
    <%= f.text_field :price %>
    <br>

    <%= f.label :log_date, "Log_Date" %>
    <%= f.datetime_select :log_date, :ampm => true, :minute_step => 15 %>
    <br>
    <%= f.label :location, "Location" %>
    <%= f.text_field :location %>
    <br>
    <%= f.label :capacity, "Capaticy" %>
    <%= f.text_field :capacity %>
    <br>
    <%= f.label :cap_unit, "Capaticy Unit" %>
    <%= f.text_field :cap_unit %>
    <br>
    <%= f.submit "Create" %>
    <br>
<% end %>

app/views/price_logs/show.html.erb
<%= @price_log.price %>

<p><%= link_to 'Back to index', price_logs_path %> </p>

app/views/price_logs/show.js.erb
$('#content').html("<%= j(render :partial => 'price_log') %>")
             .css({ backgroundColor: '#ffff99' });

app/views/product_infos/index.html.erb
<% if current_user %>
       <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
     <%= link_to('修改密碼', edit_registration_path(:user)) %>
   <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
   <% end %>

<ul>
<% @product_infos.each do |info| %>
  <li>
    <%= info.id %>
    <%= info.vendor %>
    <%= info.name %>
    <br>
    類別:<%= info.category.try(:name) %>
    <br>
    <%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    價格記錄: <%= link_to 'add log', new_price_log_path(info) %> <br>
    <% info.price_logs.each do |log| %>
      <%= log.price %>
      <%= log.location %>
      <%= log.capacity %>
      <%= log.cap_unit %>
      <%= log.log_date %>
      <br>
    <% end %>
  </li>
<% end %>
</ul>

<%= link_to 'new product info', new_product_info_path %>

app/views/product_infos/new.html.erb
<%= form_for @product_info, :url => product_infos_path do |f| %>
    <%= f.label :vendor, "廠商" %>
    <%= f.text_field :vendor %>
    <br>

    <%= f.label :name, "產品名稱" %>
    <%= f.text_field :name %>
    <br>

    <%= f.select :category_id, category_options %>
    <br>

    <%= f.submit "Create" %>
    <br>
<% end %>

app/views/users/price_logs/_price_log.html.erb
<p>Title</p>
    
<%= label_tag :price, "Price" %>
<%= text_field_tag :price, "xxx", :id => "price_text" %>
<br>
<%= label_tag :location, "Location" %>
<%= text_field_tag :location %>
<br>
<%= label_tag :capacity, "Capaticy" %>
<%= text_field_tag :capacity %>
<br>
<%= label_tag :cap_unit, "Capaticy Unit" %>
<%= text_field_tag :cap_unit %>
<br>
<%= submit_tag "Create" %>
<br>

app/views/users/price_logs/index.html.erb
<% if current_user %>
       <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
     <%= link_to('修改密碼', edit_registration_path(:user)) %>
   <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
   <% end %>

<ul>
<% @price_logs.each do |log| %>
  <li>
    <%= log.price %>
    <%#= log.location %>
    <%#= log.capacity %>
    <%#= log.cap_unit %>
    <%= log.log_date %>
    <br>

    <%= log.product_info.vendor %>
    <%= log.product_info.name %>
    <br>
    類別:<%= log.product_info.category.try(:name) %>
    <br>

  </li>
<% end %>
</ul>

<%= paginate @price_logs %>

<%= link_to '新增記錄', new_users_price_log_path %><br> 
<%= link_to '返回全體購買記錄頁面', price_logs_path %><br> 

app/views/users/price_logs/new.html.erb
<% content_for :title do %>
adf
<% end %>

<%= form_for @price_log, :url => users_price_logs_path do |f| %>
    <%= f.select :product_info_id, product_info_options, {:prompt => 'select Item'}, {:onchange => 'price_log_product_info_change()'} %>
    <br>
    <div id="price_log_info_content" style="display:none">
        <%= f.label :log_date, "Log_Date" %>
        <%= f.date_select :log_date, {selected: Date.today} %>
        <br>

        <%= f.label :price, "Price" %>
        <%= select_tag :price_select, "" %>
        <%= f.text_field :price %>
        <br>
        <%= f.label :location_id, "Location" %>
        <%= f.select :location_id, [] %>
        <br>
        <%= f.label :capacity_id, "Capacity" %>
        <%= f.select :capacity_id, [] %>
        <br>
        <%= f.submit "Create" %>
        <br>
    </div>
<% end %>

app/views/users/price_logs/product_info_logs.js.erb
$('#price_log_info_content').css({ display: ''});

$("#price_select option").remove();
<% @price_logs_for_product_info.each do |log| %>
  $("#price_select").append($("<option></option>").attr("value", '<%= log.price %>').text('<%= log.price %>'));
<% end %>
$("#price_select").append($("<option></option>").attr("value", '0').text('其他'));

$("#price_log_location_id option").remove();
<% @locations_for_product_info.each do |location| %>
  $("#price_log_location_id").append($("<option></option>").attr("value", '<%= location.id %>').text('<%= location.name %>'));
<% end %>

$("#price_log_capacity_id option").remove();
<% @capacities_for_product_info.each do |capacity| %>
  $("#price_log_capacity_id").append($("<option></option>").attr("value", '<%= capacity.id %>').text('<%= capacity.amount.to_s + " " + capacity.unit %>'));
<% end %>

$(document).ready(function() {
    return $('#price_select').change(function() {
      var item_value;
      item_value = $('#price_select').val();

      if (item_value == 0) {
        $('#price_log_price').css({ display: ''});
      } else {
        $('#price_log_price').css({ display: 'none'});
        $('#price_log_price').val(item_value);
      }
    });
  });